version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: garod004-apps-realassessoria_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/garod004/real-assessoria:latest
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: realassessoria
      DB_PASS: realassessoria_db_pass
      DB_NAME: realassessoria
    volumes:
      - ${APP_DATA_DIR}/uploads:/var/www/html/uploads_cnis
      - ${APP_DATA_DIR}/logs:/var/www/html/logs
      - ${APP_DATA_DIR}/backups:/var/www/html/backups

  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_DATABASE: realassessoria
      MYSQL_USER: realassessoria
      MYSQL_PASSWORD: realassessoria_db_pass
      MYSQL_ROOT_PASSWORD: realassessoria_root_pass
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql
