CREATE TABLE IF NOT EXISTS processos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT NOT NULL,
    usuario_cadastro_id INT NOT NULL,
    numero_processo VARCHAR(80) NOT NULL,
    orgao VARCHAR(120) DEFAULT NULL,
    assunto VARCHAR(180) DEFAULT NULL,
    fase VARCHAR(80) DEFAULT NULL,
    status VARCHAR(60) DEFAULT 'ativo',
    data_distribuicao DATE DEFAULT NULL,
    data_ultimo_andamento DATE DEFAULT NULL,
    observacoes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_processo_numero UNIQUE (numero_processo),
    CONSTRAINT fk_processos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_processos_usuario FOREIGN KEY (usuario_cadastro_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    INDEX idx_processos_cliente (cliente_id),
    INDEX idx_processos_status (status),
    INDEX idx_processos_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tarefas_prazos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT DEFAULT NULL,
    processo_id INT UNSIGNED DEFAULT NULL,
    usuario_responsavel_id INT NOT NULL,
    usuario_cadastro_id INT NOT NULL,
    titulo VARCHAR(160) NOT NULL,
    descricao TEXT,
    tipo VARCHAR(60) DEFAULT 'tarefa',
    prioridade VARCHAR(20) DEFAULT 'media',
    status VARCHAR(20) DEFAULT 'aberta',
    data_vencimento DATE NOT NULL,
    hora_vencimento TIME DEFAULT NULL,
    concluida_em DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_tarefas_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,
    CONSTRAINT fk_tarefas_processo FOREIGN KEY (processo_id) REFERENCES processos(id) ON DELETE SET NULL,
    CONSTRAINT fk_tarefas_responsavel FOREIGN KEY (usuario_responsavel_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT fk_tarefas_cadastro FOREIGN KEY (usuario_cadastro_id) REFERENCES usuarios(id) ON DELETE RESTRICT,
    INDEX idx_tarefas_vencimento (data_vencimento),
    INDEX idx_tarefas_status (status),
    INDEX idx_tarefas_responsavel (usuario_responsavel_id),
    INDEX idx_tarefas_cliente (cliente_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
