version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: garod004-apps-video-downloader_server_1
      APP_PORT: 8090

  server:
    image: ghcr.io/garod004/yt-downloader:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/downloads:/app/downloads
    environment:
      DOWNLOAD_DIR: /app/downloads
      DB_PATH: /app/data/downloads.db
